services:
  app:
    build: .
    restart: unless-stopped
    container_name: cstmr-portal-app
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      DATABASE_URL: postgresql://cstmr:${POSTGRES_PASSWORD}@10.199.206.112:5432/cstmr_portal
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - portal-uploads:/app/public/uploads

volumes:
  portal-uploads: